FROM node:22 AS builder 

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install tsx

COPY . .

RUN npm run build


FROM node:22-bullseye

WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json ./ 

COPY --from=builder /app/dist /app/dist

RUN npm install --omit=dev 

EXPOSE 4000

CMD ["node","dist/server.js"]
