version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules # This ensures node_modules stays inside the container
    env_file:
      - .env
    command: npm run dev
